var Fraction=[
    {
        content:[
            {text:'经常学习和采用新颖的做事方式',num:7},
            {text:'经常突破常规思考且方法行之有效',num:11},
            {text:'经常用熟悉的方法来解决新问题',num:3}
        ],
        index:1,
        url:'../number/s1.png'
    },
    {
        content:[
            {text:'知人善用',num:11},
            {text:'事事亲力亲为',num:3},
            {text:'总是倾听下属发言后才表达意见',num:7},
        ],
        index:2,
        url:'../number/s2.png'
    },
    {
        content:[
            {text:'只管今日事，明天的事到时再说',num:7},
            {text:'听话照做、埋头苦干',num:3},
            {text:'善于总结、分析',num:11},
        ],
        index:3,
        url:'../number/s3.png'
    },
    {
        content:[
            {text:'工作界限清晰，做好分内工作',num:3},
            {text:'从不计较个人得失',num:11},
            {text:'充满激情',num:7},
        ],
        index:4,
        url:'../number/s4.png'
    },
    {
        content:[
            {text:'有很多有效的自我解压方法',num:7},
            {text:'越挫越勇',num:11},
            {text:'追求完美，不达预期，难以宽恕自己',num:3},
        ],
        index:5,
        url:'../number/s5.png'
    },
    {
        content:[
            {text:'善于欣赏、接纳他人',num:11},
            {text:'认为自己的行为都是为对方好',num:3},
            {text:'经常换位思考',num:7},
        ],
        index:6,
        url:'../number/s6.png'
    },
    {
        content:[
            {text:'只要能报销，缺什么就买什么',num:3},
            {text:'钱能用在刀刃上',num:7},
            {text:'注重投入与产出比、性价比',num:11},
        ],
        index:7,
        url:'../number/s7.png'
    },
    {
        content:[
            {text:'赏罚分明，奖惩及时',num:11},
            {text:'注重团队激励平衡，推行平均激励',num:3},
            {text:'能及时关注下属的自我发展需求',num:7},
        ],
        index:8,
        url:'../number/s8.png'
    },
    {
        content:[
            {text:'经常需借力来解决自身专业问题',num:3},
            {text:'几乎没有遇到棘手的专业难题',num:7},
            {text:'独当一面，组织中无人可替代',num:11},
        ],
        index:9,
        url:'../number/s9.png'
    },
];

var Fractional_correspondence=[
    {
        num:[27,28,29,30,31],
        money:45000,
        content:'唉，米又涨价了',
        url:'../number/icon_6.png'
    },
    {
        num:[32,33,34,35],
        money:52000,
        content:'唉，米又涨价了',
        url:'../number/icon_6.png'
    },
    {
        num:[36,37,38,39],
        money:60000,
        content:'下月房租去哪里找？',
        url:'../number/icon_9.png'
    },
    {
        num:[40,41,42],
        money:80000,
        content:'下月房租去哪里找？',
        url:'../number/icon_9.png'
    },
    {
        num:[43,44,45],
        money:110000,
        content:'别人请客吃饭，咱只能混吃混喝',
        url:'../number/icon_1.png'
    },
    {
        num:[46,47,48],
        money:130000,
        content:'别人请客吃饭，咱只能混吃混喝？',
        url:'../number/icon_1.png'
    },
    {
        num:[49,50,51,52],
        money:150000,
        content:'当月光洒在我的脸上，我的钱包又变了模样',
        url:'../number/icon_2.png'
    },
    {
        num:[53,54,55,56],
        money:170000,
        content:'当月光洒在我的脸上，我的钱包又变了模样',
        url:'../number/icon_2.png'
    },
    {
        num:[57,58,59,60],
        money:190000,
        content:'偶尔潇洒潇洒木有问题',
        url:'../number/icon_7.png'
    },
    {
        num:[61,62,63,64],
        money:280000,
        content:'大金链子小手表、一天三顿小烧烤',
        url:'../number/icon_4.png'
    },
    {
        num:[65,66,67,68],
        money:350000,
        content:'大金链子小手表、一天三顿小烧烤',
        url:'../number/icon_4.png'
    },
    {
        num:[69,70,71,72],
        money:420000,
        content:'大众本田toyota，福特现代斯柯达？',
        url:'../number/icon_5.png'
    },
    {
        num:[73,74,75,76],
        money:480000,
        content:'大众本田toyota，福特现代斯柯达',
        url:'../number/icon_6.png'
    },
    {
        num:[77,78,79,80],
        money:600000,
        content:'小三小四走起来',
        url:'../number/icon_10.png'
    },
    {
        num:[82,83,84,85],
        money:650000,
        content:'小三小四走起来',
        url:'../number/icon_10.png'
    },
    {
        num:[86,87,88],
        money:680000,
        content:'亲爱的，下个月该换啥车呢？',
        url:'../number/icon_8.png'
    },
    {
        num:[89,90,91,92],
        money:720000,
        content:'亲爱的，下个月该换啥车呢？',
        url:'../number/icon_8.png'
    },
    {
        num:[93,94,95,96],
        money:880000,
        content:'出任CEO，赢取白富美，从此走上人生巅峰',
        url:'../number/icon_3.png'
    },
    {
        num:[97,98,99],
        money:1000000,
        content:'出任CEO，赢取白富美，从此走上人生巅峰',
        url:'../number/icon_3.png'
    },
];
